---
# Create/refresh the no-subscription repo file.
- name: Write PVE no-subscription repo
  ansible.builtin.template:
    src: pve-no-subscription.list.j2
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
